server:
  port: 8082

spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb+srv://gamikakj:NrlXtiLJZ4VeZzQU@cluster0.w2d9zk6.mongodb.net/fitnessactivity_db?retryWrites=true&w=majority
      database: fitnessactivity_db